(function(){
  'use strict';
  var es={kicker:'Una guía gratuita',title:'Antes de enviar: 3 mensajes para conversaciones difíciles',intro:'Ten claro lo que quieres decir. Encuentra las palabras. Elige una opción para decir que no, pedir claridad o disculparte, y adáptala a tu situación.',signupTitle:'Guarda estos mensajes en tu correo.',signupBody:'Recibe los tres mensajes en español e inglés, junto con consejos ocasionales de Social Receipt. No hace falta compartir mensajes privados.',emailLabel:'Tu correo electrónico',submit:'Envíame los 3 mensajes',consent:'Al registrarte, aceptas recibir estos mensajes y consejos ocasionales de Social Receipt. Puedes darte de baja cuando quieras.',readNow:'Leer los mensajes ahora',scriptsHeading:'Empieza por el que necesitas hoy.',oneKicker:'01 / Decir que no',oneTitle:'Una respuesta clara, sin un párrafo entero.',oneWhen:'Cuando te piden cubrir otro turno o cambiar tus planes, y tu respuesta es no.',oneScript:'No puedo cubrir este turno.',oneWarm:'Una opción más cálida: «Gracias por preguntar. No estoy disponible esta vez».',oneTip:'Ofrece una alternativa solo si de verdad quieres cumplirla. Si tu respuesta es sí, di que sí; una herramienta no debe convertirla en un rechazo.',twoKicker:'02 / Pedir claridad',twoTitle:'Pregunta antes de llenar los vacíos.',twoWhen:'Cuando un mensaje como «¿Podemos hablar mañana?» te hace imaginar qué significa.',twoScript:'Claro. ¿De qué quieres hablar para poder prepararme?',twoTip:'Un mensaje breve no revela las intenciones de alguien. Pide la información que necesitas, o espera a la conversación si no necesitas una respuesta ahora.',threeKicker:'03 / Disculparse',threeTitle:'Nombra lo que hiciste.',threeWhen:'Cuando quieres reparar algo que dijiste o hiciste.',threeScript:'Perdón por haberte hablado así. No estuvo bien.',threeTip:'Añade una acción de reparación que puedas cumplir. Puedes asumir la responsabilidad por tu conducta y hablar después de tus propias inquietudes.',checkTitle:'Tu revisión de 20 segundos.',checkOne:'¿Qué quiero lograr con este mensaje: decir que no, pedir claridad o reparar?',checkTwo:'¿Las palabras lo expresan directamente?',checkThree:'¿Estoy suponiendo cuáles son sus intenciones?',appCta:'Abrir Social Receipt',limits:'Social Receipt revisa señales en las palabras. No puede conocer las intenciones de alguien ni garantizar el resultado. Estos mensajes son puntos de partida, no promesas sobre una respuesta.',footer:'Social Receipt · También disponible en inglés.',back:'Volver a Social Receipt'};
  var en={}; document.querySelectorAll('[data-text]').forEach(function(e){en[e.dataset.text]=e.textContent;});
  var lang='en';try{lang=localStorage.getItem('sr_app_language')==='es'?'es':'en';}catch(e){}
  function render(){document.documentElement.lang=lang;var copy=lang==='es'?es:en;document.querySelectorAll('[data-text]').forEach(function(e){e.textContent=copy[e.dataset.text];});var b=document.getElementById('language');b.textContent=lang==='es'?'English':'Español';b.setAttribute('aria-label',lang==='es'?'Cambiar a inglés':'Switch to Spanish');}
  function track(name){if(window.SRAnalytics)window.SRAnalytics.track(name,{feature_name:'scripts_toolkit'});}
  document.getElementById('language').addEventListener('click',function(){lang=lang==='en'?'es':'en';try{localStorage.setItem('sr_app_language',lang);}catch(e){}render();});render();
  document.querySelectorAll('[data-copy]').forEach(function(b){b.addEventListener('click',async function(){var text=document.getElementById(b.dataset.copy).textContent;try{await navigator.clipboard.writeText(text);b.textContent=lang==='es'?'Copiado':'Copied';track('script_copied');}catch(e){b.textContent=lang==='es'?'Selecciona el texto para copiarlo':'Select the text to copy';} });});
  document.getElementById('gift-email-form').addEventListener('submit',async function(event){event.preventDefault();var form=event.currentTarget;if(!form.reportValidity())return;var button=document.getElementById('submit'),status=document.getElementById('status');button.disabled=true;button.textContent=lang==='es'?'Guardando…':'Saving…';status.textContent='';try{var response=await fetch('/.netlify/functions/subscribe-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('gift-email').value.trim()})});var data=await response.json();if(!response.ok||!data.ok)throw new Error('signup_failed');status.textContent=lang==='es'?'Ya estás en la lista. Si es tu primer registro, busca los mensajes en tu correo, incluido spam. Confirma tu suscripción para recibir los próximos consejos. También puedes leerlos abajo.':'You’re on the list. If this is your first signup, look for the scripts in your inbox or spam folder. Confirm your subscription to receive future tips. You can also read them below.';track('email_capture_completed');form.reset();}catch(e){status.textContent=lang==='es'?'No pudimos conectar con la lista de correo. Inténtalo de nuevo. Los mensajes siguen disponibles abajo.':'We couldn’t connect to the email list. Please try again. The scripts are still available below.';track('email_capture_failed');}finally{button.disabled=false;button.textContent=(lang==='es'?es:en).submit;}});
})();
